"""empty message

Revision ID: 0ce920d5ffbc
Revises: de2c89fe5027
Create Date: 2016-06-16 13:42:46.013430

"""

# revision identifiers, used by Alembic.
revision = '0ce920d5ffbc'
down_revision = 'de2c89fe5027'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('general', sa.Enum('Off Campus', 'Outside On Campus', 'Residence Hall', 'Other Campus Building', name='general_enum'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'general')
    ### end Alembic commands ###
