"""empty message

Revision ID: 124c4da63a61
Revises: 0ce920d5ffbc
Create Date: 2016-06-22 17:17:39.778516

"""

# revision identifiers, used by Alembic.
revision = '124c4da63a61'
down_revision = '0ce920d5ffbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mapping_incident_id_fkey', 'mapping', type_='foreignkey')
    op.create_foreign_key(None, 'mapping', 'incidents', ['incident_id'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mapping', type_='foreignkey')
    op.create_foreign_key('mapping_incident_id_fkey', 'mapping', 'incidents', ['incident_id'], ['id'])
    ### end Alembic commands ###
