"""empty message

Revision ID: 21050083d789
Revises: ab67b5dfc9c0
Create Date: 2016-06-09 16:32:44.078322

"""

# revision identifiers, used by Alembic.
revision = '21050083d789'
down_revision = 'ab67b5dfc9c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('admin')
    ### end Alembic commands ###
