"""empty message

Revision ID: 44e73da87bc1
Revises: e496d825d4b0
Create Date: 2016-07-18 13:44:56.338110

"""

# revision identifiers, used by Alembic.
revision = '44e73da87bc1'
down_revision = 'e496d825d4b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_summary_search_vector', table_name='incidents')
    op.drop_column('incidents', 'summary_search_vector')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('summary_search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_incidents_summary_search_vector', 'incidents', ['summary_search_vector'], unique=False)
    ### end Alembic commands ###
