"""empty message

Revision ID: 5753047047e8
Revises: adfcb7e39450
Create Date: 2016-07-28 17:45:28.638762

"""

# revision identifiers, used by Alembic.
revision = '5753047047e8'
down_revision = 'adfcb7e39450'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typecategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('types', sa.Column('typecategory', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'types', 'typecategories', ['typecategory'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'types', type_='foreignkey')
    op.drop_column('types', 'typecategory')
    op.drop_table('typecategories')
    ### end Alembic commands ###
