"""empty message

Revision ID: 71548426d5e6
Revises: 21050083d789
Create Date: 2016-06-13 11:41:45.457675

"""

# revision identifiers, used by Alembic.
revision = '71548426d5e6'
down_revision = '21050083d789'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_locations', sa.Column('oncampus', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general_locations', 'oncampus')
    ### end Alembic commands ###
