"""empty message

Revision ID: adfcb7e39450
Revises: 44e73da87bc1
Create Date: 2016-07-28 17:29:09.932271

"""

# revision identifiers, used by Alembic.
revision = 'adfcb7e39450'
down_revision = '44e73da87bc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupmapping',
    sa.Column('loc_id', sa.Integer(), nullable=True),
    sa.Column('locgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loc_id'], ['locations.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['locgroup_id'], ['locgroups.id'], ondelete='cascade')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupmapping')
    op.drop_table('locgroups')
    ### end Alembic commands ###
