"""empty message

Revision ID: c33266fc7ff6
Revises: 124c4da63a61
Create Date: 2016-06-27 11:38:49.499444

"""

# revision identifiers, used by Alembic.
revision = 'c33266fc7ff6'
down_revision = '124c4da63a61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mapping_type_id_fkey', 'mapping', type_='foreignkey')
    op.create_foreign_key(None, 'mapping', 'types', ['type_id'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mapping', type_='foreignkey')
    op.create_foreign_key('mapping_type_id_fkey', 'mapping', 'types', ['type_id'], ['id'])
    ### end Alembic commands ###
