"""empty message

Revision ID: e496d825d4b0
Revises: None
Create Date: 2016-07-18 12:06:37.159532

"""

# revision identifiers, used by Alembic.
revision = 'e496d825d4b0'
down_revision = None

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('summary_search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_summary_search_vector', 'incidents', ['summary_search_vector'], unique=False, postgresql_using='gin')
    op.create_table('mapping',
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='cascade')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapping')
    op.drop_index('ix_incidents_summary_search_vector', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('types')
    op.drop_table('locations')
    ### end Alembic commands ###
