"""empty message

Revision ID: f4f00d456287
Revises: a6d7d6a7ef39
Create Date: 2016-06-09 11:49:16.468004

"""

# revision identifiers, used by Alembic.
revision = 'f4f00d456287'
down_revision = 'a6d7d6a7ef39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('location', sa.String(length=25), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'location')
    ### end Alembic commands ###
